# Generated by Django 6.0 on 2025-12-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
