# Generated by Django 6.0 on 2025-12-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_phones_brand_delete_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
